vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: /build/images
            upload_destination: '%kernel.project_dir%/public/build/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer